services:
  uhf-server-remux:
    build: .
    container_name: uhf-server-remux
    restart: unless-stopped
    networks:
      - docker_default
    env_file:
      - .env
    environment:
      - WATCH_FOLDER
      - DESTINATION_FOLDER
      - INTERVAL
      - MAX_JOBS
      - TZ
      - PUID
      - PGID
      - PLEX_URL
      - PLEX_TOKEN
      - PLEX_LIBRARY
      - PLEX_SCAN_COUNT
      - PLEX_FOLDER
      - DB_PATH
      - REMUX_FILE
      - DB_FILE
      - INCLUDE_CANCELLED
      - THRESHOLD
      - LANGUAGE
    volumes:
      - ${WATCH_FOLDER}:/recordings
      - ${DESTINATION_FOLDER}:/remux
      - ${DB_PATH}:/data:ro

# Default Network
networks:
  docker_default:
    external: true
